import React from 'react';
import ScrollSection from '@/components/ui/scroll-section';

const disclaimerSections = [
  {
    title: '1. Platform in Beta Phase',
    content: `This website, including all features, content, and functionality (collectively, the "Platform"), is operated by NeuralArc Global Pvt Ltd ("NeuralArc", "we", "us", or "our") and is currently made available in beta for testing, evaluation, and limited public preview.\nThe Platform is provided strictly on an "as is," "as available," and experimental basis. NeuralArc makes no representations or warranties of any kind, express or implied, regarding the reliability, accuracy, or completeness of the Platform at this stage.`
  },
  {
    title: '2. No Professional Advice',
    content: `All information and content made available through this Platform, including AI-generated outputs, is for informational and illustrative purposes only.\nNothing on this Platform constitutes or shall be construed as legal, medical, financial, investment, business, or other professional advice. Users are solely responsible for independently verifying any information obtained through the Platform before acting or making decisions based on it.`
  },
  {
    title: '3. Artificial Intelligence and Output Liability',
    content: `The Platform may use AI, machine learning, or large language models to generate content. You acknowledge and accept that:\n• AI-generated content may be factually incorrect, incomplete, or biased;\n• Outputs are not guaranteed to be accurate, truthful, or contextually appropriate;\n• NeuralArc disclaims all liability for reliance on AI-generated outputs.\nBy using the Platform, you agree not to rely on AI-generated content for decisions of a personal, professional, legal, or financial nature without consulting qualified professionals.`
  },
  {
    title: '4. Limitation of Liability',
    content: `To the maximum extent permitted under applicable law, NeuralArc, its officers, directors, shareholders, affiliates, contractors, licensors, and employees shall not be liable for any direct, indirect, incidental, consequential, special, exemplary, or punitive damages arising out of or related to:\n• access to, use of, or inability to use the Platform;\n• errors, omissions, delays, or performance issues;\n• content generated by AI or user input;\n• cyberattacks, data loss, unauthorized access, or security breaches.\nThis limitation applies even if NeuralArc has been advised of the possibility of such damages, and regardless of the legal theory (contract, tort, strict liability, or otherwise) upon which the claim is based.`
  },
  {
    title: '5. Third-Party Services and Hosting',
    content: `This Platform is hosted on infrastructure provided by Vercel Inc. NeuralArc does not control Vercel's operations, security, or data policies.\nBy using this Platform, you consent to your data being processed and stored by Vercel and its subprocessors in accordance with their respective terms of service and privacy policies.\nThe Platform may also link to or incorporate third-party services or tools. NeuralArc accepts no responsibility or liability for any third-party content, data practices, or service reliability.`
  },
  {
    title: '6. Intellectual Property',
    content: `All intellectual property on this Platform—including, without limitation, code, software, content, branding, design elements, and AI-generated materials—are the exclusive property of NeuralArc or its licensors and are protected by applicable copyright, trademark, and patent laws.\nYou may not copy, reproduce, distribute, or use any part of the Platform without express prior written consent. Unauthorized use may result in civil and/or criminal liability.`
  },
  {
    title: '7. User Conduct and Acceptable Use',
    content: `You agree not to use the Platform for any unlawful, harmful, or unethical purpose. Prohibited uses include, but are not limited to:\n• Attempting to reverse-engineer or exploit the AI systems;\n• Uploading malicious code or compromising Platform security;\n• Generating content that is defamatory, infringing, obscene, deceptive, or discriminatory;\n• Circumventing usage limits, access controls, or platform restrictions.\nViolation of these terms may result in immediate suspension or termination of access and may expose you to civil or criminal liability.`
  },
  {
    title: '8. Jurisdiction and Governing Law',
    content: `This Disclaimer and all matters arising from the use of this Platform shall be governed by and construed in accordance with the laws of India, without regard to conflict of laws.\nYou expressly submit to the exclusive jurisdiction of the courts of Pune, Maharashtra, for the resolution of any disputes.`
  },
  {
    title: '9. Changes to this Disclaimer',
    content: `NeuralArc reserves the right to amend, revise, or update this Disclaimer at any time without prior notice. Continued use of the Platform following any updates constitutes acceptance of the revised terms.`
  },
  {
    title: '10. Contact Information',
    content: `For questions, legal concerns, or notices related to this Disclaimer, please contact: support@neuralarc.ai`
  }
];

export default function DisclaimerPage() {
  return (
    <div className="max-w-[1920px] mx-auto md:px-8 px-4 flex flex-col items-center space-y-8 pb-8">
      {/* Banner */}
      <ScrollSection>
        <div className="w-full relative flex items-center h-[216px] lg:h-[516px] justify-center bg-[url('/images/legal/disclaimer-banner.png')] bg-cover bg-center rounded-2xl overflow-hidden">
          <div className="relative z-10 flex flex-col items-center">
            <h1 className="text-4xl lg:text-7xl text-[#392E26] font-semibold mb-4 tracking-tight">Disclaimer</h1>
            <span className="text-base lg:text-[28px]">Effective Date: April, 2025</span>
          </div>
        </div>
      </ScrollSection>
      {/* Content */}
      <ScrollSection>
        <div className="w-full -mt-8 p-6 md:p-10 z-20 relative mx-auto max-w-[1820px]">
          {disclaimerSections.map((section) => (
            <div key={section.title} className="mb-8 last:mb-0">
              <h2 className="font-semibold text-lg lg:text-[32px] mb-2">{section.title}</h2>
              <p className="font-light text-sm lg:text-2xl">{section.content}</p>
            </div>
          ))}
        </div>
      </ScrollSection>
    </div>
  );
} 